<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Terminal.Core/Terminal.Core.csproj" />
    <ProjectReference Include="../Terminal.Execution/Terminal.Execution.csproj" />
    <ProjectReference Include="../Terminal.Protocol/Terminal.Protocol.csproj" />
  </ItemGroup>
</Project>
